### PR TITLE
11 basic acceptance fixes #11

### LINKED ISSUE #11: Basic Acceptance Testing
Create project Acceptance (Linux)

Use Catch for asserts/cases.

Input: dataset (GeocodeJSON), API call(s), expected results

Output: text report (pass/fail)

Error code if (unexpected) exception thrown.

### PR DESCRIPTION
**Pull request by boshkins**
to see this in action, type

```
git checkout 11-basic-acceptance
cd pelopia/build/make
make accept
```

This is what I see:

```
/home/boshkins/github/pelopia/build/make> make accept
g++ -c -std=c++11 -o /home/boshkins/github/pelopia/linux-x86_64-Debug/obj/src/Pelopia.o /home/boshkins/github/pelopia/src/Pelopia.cpp -I. -I/home/boshkins/github/pelopia/inc
g++ -c -std=c++11 -o /home/boshkins/github/pelopia/linux-x86_64-Debug/obj/src/Dataset.o /home/boshkins/github/pelopia/src/Dataset.cpp -I. -I/home/boshkins/github/pelopia/inc
g++ -c -std=c++11 -o /home/boshkins/github/pelopia/linux-x86_64-Debug/obj/src/GeocodeJSON.o /home/boshkins/github/pelopia/src/GeocodeJSON.cpp -I. -I/home/boshkins/github/pelopia/inc
g++ -c -std=c++11 -o /home/boshkins/github/pelopia/linux-x86_64-Debug/obj/src/Response.o /home/boshkins/github/pelopia/src/Response.cpp -I. -I/home/boshkins/github/pelopia/inc
ar -rc /home/boshkins/github/pelopia/linux-x86_64-Debug/lib/libpelopia.a /home/boshkins/github/pelopia/linux-x86_64-Debug/obj/src/Pelopia.o /home/boshkins/github/pelopia/linux-x86_64-Debug/obj/src/Dataset.o /home/boshkins/github/pelopia/linux-x86_64-Debug/obj/src/GeocodeJSON.o /home/boshkins/github/pelopia/linux-x86_64-Debug/obj/src/Response.o 
make -C acceptance
make[1]: Entering directory '/home/boshkins/github/pelopia/build/make/acceptance'
g++ -o /home/boshkins/github/pelopia/linux-x86_64-Debug/bin/acceptance /home/boshkins/github/pelopia/linux-x86_64-Debug/obj/acceptance/main.o /home/boshkins/github/pelopia/linux-x86_64-Debug/lib/libpelopia.a 
/home/boshkins/github/pelopia/linux-x86_64-Debug/bin/acceptance

acceptance is a Catch v1.2.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
one term, no location, found
-------------------------------------------------------------------------------
/home/boshkins/github/pelopia/acceptance/main.cpp:12
...............................................................................

/home/boshkins/github/pelopia/acceptance/main.cpp:12: FAILED:
due to unexpected exception with message:
  not implemented

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed

Makefile:20: recipe for target 'accept' failed
make[1]: *** [accept] Error 1
make[1]: Leaving directory '/home/boshkins/github/pelopia/build/make/acceptance'
Makefile:33: recipe for target 'accept' failed
make: *** [accept] Error 2
```

### CODE REVIEW

**Comment by dianashk** [comment]
Valid Json must have `""` around all strings, including keys. Update the test input file.

**Comment by dianashk** [comment]
Everything else looks good :+1:

**Comment by boshkins** [comment]
time to merge/close?

**Comment by boshkins** [comment]
Travis fails because CI is not set up on this branch yet (see #13)

**Pull request merged**
